-- Create Schema
DROP SCHEMA IF EXISTS MoodMingle;
CREATE SCHEMA MoodMingle;
USE MoodMingle;

CREATE TABLE Users (
    userID SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Preferences (
    preferenceID SERIAL PRIMARY KEY,
    userID INT REFERENCES Users(userID) ON DELETE CASCADE,
    keyword VARCHAR(100) NOT NULL -- e.g., "Horror", "Sci-Fi", "Yoga"
);

CREATE TABLE Activities (
    activityID SERIAL PRIMARY KEY,
    userID BIGINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    genre VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    weather VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE
);